### ISSUE TITLE
application :0

### ISSUE THREAD

**Issue by leanneubaldo** [Graycot/loop-ring#31]
hiya! i wanna join the webring :)) the details are the ff:

  {
        "siteOwner": "Leanne",
        "siteName": "leanne ♥",
        "siteURL": "https://leanneu.neocities.org/",
        "siteTags": "personal, blog, art, life",
        "siteShortDescription": "the personal website of some girl named leanne",
        "siteLongDescription": "hello! i'm leanne, an ict student with an interest in design and creative writing. this personal website serves as my creative haven & safe space of some sort! hope you enjoy your visit <3"
  }

**Comment by Graycot** [comment]
Website no longer exists, cannot add.
